services:
  db:
    image: postgis/postgis:15-3.3
    container_name: hadong_trafic_dbf
    environment:
      - POSTGRES_USER=trung
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=hadong_traffic
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql 

