services:
  db:
    image: postgis/postgis:15-3.3
    container_name: hadong_db
    environment:
      POSTGRES_DB: hadong_traffic
      POSTGRES_USER: trung
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trung -d hadong_traffic"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: hadong_web
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URI: postgresql://trung:123456@hadong_db:5432/hadong_traffic
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: hadong_traffic
      POSTGRES_USER: trung
      POSTGRES_PASSWORD: 123456
    ports:
      - "8501:8501"
    volumes:
      - .:/app

volumes:
  postgres_data:
    driver: local